version: '3'
services:
  api:
    image: adamfortune/adamfortunecom
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/dist
    ports:
      - "8080:8080"
    depends_on: [db]

  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/home/adam/Documents/rust-projects/adamfortunecom/postgresql/data

volumes:
  db:
    driver: local